#!/usr/bin/env bash
set -e

print_usage () {
    cat <<EOF
local-model - start a specified model locally
Usage:
    $0 [OPTIONS] SETTINGSFILE
Options:
    --model PATH   Path to model binary (default: CURRENT/model)
    --python       flag to indicate execution with python
    --logdir PATH      Directory for log output (default: CURRENT))
    --workdir PATH     Directory to work in (default: CURRENT)

EOF
    exit 1
}

# set defaults:
model="$(pwd)/model"
logdir=$(pwd)
workdir=$(pwd)
python=0
while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        --model)
            shift || print_usage
            model="$1"
            ;;
        --python)
          shift || print_usage
          python="$1"
          ;;
        --logdir)
            shift || print_usage
            logdir="$1"
            ;;
        --workdir)
            shift || print_usage
            workdir="$1"
            ;;
        *)
            if [[ -z "$settings" ]]
            then
                settings="$1"
            else
                print_usage
            fi
            ;;
    esac
    shift
done

if [[ -z "$settings" ]]
then
    print_usage
fi

if [[ ! -e "$model" ]]
then
    echo "Cannot find $model"
    exit 1
fi

mkdir -p "$workdir"
mkdir  -p "$logdir"
if [ "$python" == 1 ]
then
  echo "usr/bin/python $model --settings $settings"
  $model --settings "$settings"
else
  $model "$settings"
fi
